export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const CHANGE_APP_TITLE = 'CHANGE_APP_TITLE';
export const ON_TAB_CHANGE = 'ON_TAB_CHANGE';
export const HANDLE_REFRESH = 'HANDLE_REFRESH';
export const HANDLE_LOAD_MORE = 'HANDLE_LOAD_MORE';
export const LOAD_ACTIVITIES = 'HANDLE_LOAD_MORE';
export const SHOW_DETAIL_VIEW = 'SHOW_DETAIL_VIEW';
export const GO_HOME = 'GO_HOME';